### ISSUE TITLE
Crash opening views implemented with Jetpack Compose

### ISSUE THREAD

**Issue by d2callpod** [msintuneappsdk/intune-app-wrapping-tool-android#98]
**Questions to Ask Before Submission**
1. Does you app launch successfully without wrapping? _yes_
2. Have you reviewed the [prerequisites](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#fulfill-the-prerequisites-for-using-the-app-wrapping-tool) for App Wrapping? _yes_
3. Does your issue have a solution in the [Troubleshooting Guide?](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/wiki/Troubleshooting-the-App-Wrapper) _no_
4. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for similar issues? _yes_
5. Are you using the latest version of the App Wrapper? _yes_

**Describe the bug:**
With a wrapped apk navigating to views implemented with Jetpack Compose. There are no issues with the apk prior to wrapping.

**To Reproduce**
1. Wrap an APK with the Intune wrapping tool
2. Launch the app
3. Authenticate with Intune
4. Navigate to views that are implemented with xml layouts
5. Navigate to views implemented with Jetpack Compose
6. The app crashes with the stacktrace below

**Expected behavior:**
Jetpack Compose views open without crashing.

**Screenshots and logs:**
```
java.lang.IncompatibleClassChangeError: Found interface androidx.compose.ui.graphics.drawscope.DrawScope, but class was expected (declaration of 'androidx.compose.ui.graphics.drawscope.DrawScope' appears in /data/app/~~A2WLcqqu2Gybutp-zSRSQg==/com.keepersecurity.intune-xQXZL80eio-qnibnZdnbzg==/base.apk!classes13.dex)
    at androidx.compose.ui.graphics.drawscope.DrawScope.drawRect-n-J9OG0$default(DrawScope.kt:454)
    at androidx.compose.foundation.BackgroundNode.drawRect(Background.kt:163)
    at androidx.compose.foundation.BackgroundNode.draw(Background.kt:155)
    at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
    at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:86)
    at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:364)
    at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:54)
    at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:383)
    at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:382)
    at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
    at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
    at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
    at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
    at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:382)
    at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:380)
    at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
    at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:335)
    at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:277)
    at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:348)
    at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:176)
    at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
    at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:54)
    at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:383)
    at androidx.compose.ui.node.NodeCoordinator$drawBlock$1$1.invoke(NodeCoordinator.kt:382)
    at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2303)
    at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:500)
    at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:256)
    at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
    at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:382)
    at androidx.compose.ui.node.NodeCoordinator$drawBlock$1.invoke(NodeCoordinator.kt:380)
    at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:209)
    at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:335)
    at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:277)
    at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:348)
    at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:926)
    at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
    at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:361)
    at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:353)
    at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:926)
```

**Smartphone (please complete the following information):**
 - Device: Pixel 5a
 - OS Version: Android 14

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? `1.0.4214.3`
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Native Android
- For pre-wrapping errors, does the app build without being wrapped? _N/A_
- For post-wrapping errors, does the app launch without being wrapped? _yes_
- Who is the customer? 
- Do you see a trend with it only being reproduced on a specific device? _fails every time_.

**Additional context:**
No

**Comment by ChismanRaheem** [comment]
HI @d2callpod Please confirm that if you are using ProGuard to eliminate unused class references from the app's primary DEX file.
 Note if you are using v3.1.0 or higher of the Android Gradle plugin, disable the [D8 dexer](https://android-developers.googleblog.com/2018/04/android-studio-switching-to-d8-dexer.html)

**Comment by d2callpod** [comment]
Hi @ChismanRaheem 

We have Proguard disabled.

**Comment by ChismanRaheem** [comment]
HI @d2callpod Please provide the full crash report also provide us with sample app so that we can reproduce the issue with steps that you have provided.

**Comment by d2callpod** [comment]
@ChismanRaheem 

Here is an example apk and it's source code. 

[intune-wrapped-compose-sample-apk.zip](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/15045208/intune-wrapped-compose-sample-apk.zip)


[ComposeApplication.zip](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/15045192/ComposeApplication.zip)

**Comment by ChismanRaheem** [comment]
@d2callpod Thank you we are looking into this.

**Comment by ChismanRaheem** [comment]
@d2callpod In this situation, JetPack Compose cannot be utilized, note we are looking into this internally it is advised to use the Intune SDK in place of the wrapper.

**Comment by d2callpod** [comment]
The SDK can be used within JetPack Compose apps? From looking at the documentation I wasn't sure.

**Comment by d2callpod** [comment]
I don't want to invest any more time in Intune unless it's clear the SDK can be used. I already put a lot of time into the use of Intune. I have low expectations of this being resolved. Especially after talking with the author of this blog post.

https://www.zacsweers.dev/is-viewpump-a-security-risk/amp/

**Comment by ChismanRaheem** [comment]
Hi @d2callpod Thank you for the update and providing your feedback on the issue. I am recommending that you engage the respective repository that aligns with the incident via https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues for further investigation with the Intune app sdk for Android. 

Summary: Jetpack Compose is not supported with Intune app wrapper for Android.
